#!/bin/bash

if test -d ../alsa-lib/utils && ! test -r `aclocal --print-ac-dir`/alsa.m4; then
  alsa_m4_flags="-I ../alsa-lib/utils"
fi
aclocal $alsa_m4_flags $ACLOCAL_FLAGS
autoheader
automake --foreign --copy --add-missing
touch depcomp		# for older automake
autoconf
export CFLAGS='-O2 -Wall -pipe -g'
echo "CFLAGS=$CFLAGS"
echo "./configure $@"
./configure $@ || exit 1
unset CFLAGS
if [ -z "$CVSCOMPILE_NO_MAKE" ]; then
  make
fi
