#!/bin/bash

aclocal $ACLOCAL_FLAGS
autoheader
automake --foreign --add-missing
autoconf
export CFLAGS='-O2 -Wall -pipe -g'
echo "CFLAGS=$CFLAGS"
echo "./configure $@"
./configure $@ || exit 1
unset CFLAGS
if [ -z "$CVSCOMPILE_NO_MAKE" ]; then
  make
fi
