.TH APLAY 1 "25 Nov 1998"
.SH NAME
arecord, aplay \- command-line sound recorder and player for ALSA soundcard driver
.SH SYNOPSIS

[\fBarecord\fP | \fBaplay\fP ] [\fIflags\fP] filename

.SH DESCRIPTION
\fBarecord\fP is a command-line soundfile recorder for the ALSA soundcard
driver. It supports several file formats and multiple soundcards with
multiple devices. 

\fBaplay\fP is much the same, only it plays instead of recording. For
supported soundfile formats, the sampling rate, bit depth, and so
forth can be automatically determined from the soundfile header.

.SH INVOKING

[\fBarecord\fP | \fBaplay\fP ] [\fIflags\fP] filename

.SS Options
.TP
\fI-h, --help\fP 
Help: show syntax.
.TP
\fI-V, --version\fP
Print current version.
.TP
\fI-l\fP
List all available soundcards and devices. 
.TP
\fI-c\fP <card number>
Select the soundcard to use, if you have more than one. Cards are
numbered from 1 (the default).
.TP
\fI-d\fP <device number>
Select the soundcard device to use, if your card has more than
one. Devices are numbered from 0 (the default). Not to be confused
with the soundcard mixer channels, which are sometimes also referred
to as "devices", just to be annoying. Many soundcards will only have
device 0. Some more complex cards may have mor. Try using \fI-l\fP
and see what you get.

.TP
\fI-q\fP
Quiet mode. Suppress messages (not sound :))

.TP
\fI-w\fP 
Use Wave soundfile format (.wav)
.TP
\fI-r\fP 
Use raw soundfile format. Requires -s, -b, and -p flags?
.TP
\fI-u\fP 
Use Sparc Audio soundfile format (.au)
.TP
\fI-v\fP 
Use Voc soundfile format
.TP
\fI-S\fP 
Soundfile is stereo. Mono is the default for headerless files.
.TP
\fI-t \fP<secs>
Time limit for recording, in seconds.
.TP
\fI-s \fP<Hz> 
Sampling rate in Hertz.
.TP
\fI-b \fP<bits> 
Bit depth (8 or 16 bits).
.TP
\fI-m\fP 
Set to CD standard quality (44100 Hz, stereo, 16-bit linear).
.TP
\fI-M \fP<bits> 
Set to DAT quality (48000 Hz, stereo, 16-bit linear).
.TP
\fI-p \fP<type>
Compression type (alaw, ulaw, adpcm).

.SS
Example: 

.RS
\fBaplay -c 2 -r -u -s 22050 -b 8 -p ulaw foobar\fR

.ID
will play the raw file "foobar" as a
22050-Hz, mono, 8-bit, Mu-Law .au file, using the second soundcard. 

\fBarecord -t 10 -m -w foobar.wav\fP

will record foobar.wav as a 10-second, CD-quality wave file.

.SH SEE ALSO
\fB
alsamixer(1),
amixer(1)
\fP

.SH BUGS 
Note that .aiff files are not currently supported.

.SH AUTHOR
\fBarecord\fP and \fBaplay\fP are by Jaroslav Kysela <perex@jcu.cz>
This document is by Paul Winkler <zarmzarm@erols.com>.





