.TH ASEQSEND 1 "11 Mar 2024"

.SH NAME
aseqsend \- send arbitrary messages to selected ALSA MIDI seqencer port

.SH SYNOPSIS
\fBaseqsend\fP \-p client:port -s file-name
.br
\fBaseqsend\fP \-p client:port "hex encoded byte-string"

.SH DESCRIPTION
\fBaseqsend\fP is a command-line utility which allows one to send
SysEx (system exclusive) data to ALSA MIDI sequencer port.
It can also send any other MIDI commands.
Messages to be sent can be given in the last argument as hex encoded
byte string or can be read from raw binary file.
When sending several SysEx messages at once there is a delay of 1ms
after each message as default and can be set to different value with
option \-i.

A client can be specified by its number, its name, or a prefix of its
name.  A port is specified by its number; for port 0 of a client, the
":0" part of the port specification can be omitted.

\fBaseqsend\fP can send UMP packets as MIDI 2.0 device by specifying
via \-u option as well, while the default operation is the legacy MIDI
1.0 byte stream.

.SH OPTIONS

.TP
\fI\-h, \-\-help\fP
Prints a list of options.

.TP
\fI\-V, \-\-version\fP
Prints the current version.

.TP
\fI\-l, \-\-list\FP
Prints a list of possible output ports.

.TP
\fI\-v, \-\-verbose\fP
Prints number of bytes actually sent

.TP
\fI\-p, -\-port=client:port\fP
Target port by number or name

.TP
\fI\-s, \-\-file=filename\fP
Send raw binary data from given file name

.TP
\fI\-i, \-\-interval=msec\fP
Interval between SysEx messages in milliseconds

.TP
\fI\-u, \-\-ump=version\fP
Specify the MIDI version. 0 for the legacy MIDI 1.0 (default),
1 for UMP MIDI 1.0 protocol and 2 for UMP MIDI 2.0 protocol.

When UMP MIDI 1.0 or MIDI 2.0 protocol is specified, \fBaseqsend\fP
reads the input as raw UMP packets, 4 each byte in big endian.

.SH EXAMPLES

\fBaseqsend -p 128:0 "F0 41 10 00 00 64 12 18 00 21 06 59 41 59 4E F7"\fP

\fBaseqsend -p 128:0 -s I7BulkDump.syx\fP

.SH SEE ALSO
\fBaseqdump(1)\fP

.SH AUTHOR
Miroslav Kovac <mixxoo@gmail.com>
